// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CloudInit
{
    [Obsolete(@"This resource is deprecated.
Please use the getConfig data source instead.")]
    [CloudInitResourceType("cloudinit:index/config:Config")]
    public partial class Config : global::Pulumi.CustomResource
    {
        [Output("base64Encode")]
        public Output<bool?> Base64Encode { get; private set; } = null!;

        [Output("boundary")]
        public Output<string?> Boundary { get; private set; } = null!;

        [Output("gzip")]
        public Output<bool?> Gzip { get; private set; } = null!;

        [Output("parts")]
        public Output<ImmutableArray<Outputs.ConfigPart>> Parts { get; private set; } = null!;

        /// <summary>
        /// rendered cloudinit configuration
        /// </summary>
        [Output("rendered")]
        public Output<string> Rendered { get; private set; } = null!;


        /// <summary>
        /// Create a Config resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Config(string name, ConfigArgs args, CustomResourceOptions? options = null)
            : base("cloudinit:index/config:Config", name, args ?? new ConfigArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Config(string name, Input<string> id, ConfigState? state = null, CustomResourceOptions? options = null)
            : base("cloudinit:index/config:Config", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Config resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Config Get(string name, Input<string> id, ConfigState? state = null, CustomResourceOptions? options = null)
        {
            return new Config(name, id, state, options);
        }
    }

    public sealed class ConfigArgs : global::Pulumi.ResourceArgs
    {
        [Input("base64Encode")]
        public Input<bool>? Base64Encode { get; set; }

        [Input("boundary")]
        public Input<string>? Boundary { get; set; }

        [Input("gzip")]
        public Input<bool>? Gzip { get; set; }

        [Input("parts", required: true)]
        private InputList<Inputs.ConfigPartArgs>? _parts;
        public InputList<Inputs.ConfigPartArgs> Parts
        {
            get => _parts ?? (_parts = new InputList<Inputs.ConfigPartArgs>());
            set => _parts = value;
        }

        public ConfigArgs()
        {
        }
        public static new ConfigArgs Empty => new ConfigArgs();
    }

    public sealed class ConfigState : global::Pulumi.ResourceArgs
    {
        [Input("base64Encode")]
        public Input<bool>? Base64Encode { get; set; }

        [Input("boundary")]
        public Input<string>? Boundary { get; set; }

        [Input("gzip")]
        public Input<bool>? Gzip { get; set; }

        [Input("parts")]
        private InputList<Inputs.ConfigPartGetArgs>? _parts;
        public InputList<Inputs.ConfigPartGetArgs> Parts
        {
            get => _parts ?? (_parts = new InputList<Inputs.ConfigPartGetArgs>());
            set => _parts = value;
        }

        /// <summary>
        /// rendered cloudinit configuration
        /// </summary>
        [Input("rendered")]
        public Input<string>? Rendered { get; set; }

        public ConfigState()
        {
        }
        public static new ConfigState Empty => new ConfigState();
    }
}
