// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudinit.outputs;

import com.pulumi.cloudinit.outputs.GetConfigPart;
import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetConfigResult {
    private @Nullable Boolean base64Encode;
    private @Nullable String boundary;
    private @Nullable Boolean gzip;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    private List<GetConfigPart> parts;
    /**
     * @return The final rendered multi-part cloud-init config.
     * 
     */
    private String rendered;

    private GetConfigResult() {}
    public Optional<Boolean> base64Encode() {
        return Optional.ofNullable(this.base64Encode);
    }
    public Optional<String> boundary() {
        return Optional.ofNullable(this.boundary);
    }
    public Optional<Boolean> gzip() {
        return Optional.ofNullable(this.gzip);
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    public List<GetConfigPart> parts() {
        return this.parts;
    }
    /**
     * @return The final rendered multi-part cloud-init config.
     * 
     */
    public String rendered() {
        return this.rendered;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetConfigResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Boolean base64Encode;
        private @Nullable String boundary;
        private @Nullable Boolean gzip;
        private String id;
        private List<GetConfigPart> parts;
        private String rendered;
        public Builder() {}
        public Builder(GetConfigResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.base64Encode = defaults.base64Encode;
    	      this.boundary = defaults.boundary;
    	      this.gzip = defaults.gzip;
    	      this.id = defaults.id;
    	      this.parts = defaults.parts;
    	      this.rendered = defaults.rendered;
        }

        @CustomType.Setter
        public Builder base64Encode(@Nullable Boolean base64Encode) {

            this.base64Encode = base64Encode;
            return this;
        }
        @CustomType.Setter
        public Builder boundary(@Nullable String boundary) {

            this.boundary = boundary;
            return this;
        }
        @CustomType.Setter
        public Builder gzip(@Nullable Boolean gzip) {

            this.gzip = gzip;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetConfigResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder parts(List<GetConfigPart> parts) {
            if (parts == null) {
              throw new MissingRequiredPropertyException("GetConfigResult", "parts");
            }
            this.parts = parts;
            return this;
        }
        public Builder parts(GetConfigPart... parts) {
            return parts(List.of(parts));
        }
        @CustomType.Setter
        public Builder rendered(String rendered) {
            if (rendered == null) {
              throw new MissingRequiredPropertyException("GetConfigResult", "rendered");
            }
            this.rendered = rendered;
            return this;
        }
        public GetConfigResult build() {
            final var _resultValue = new GetConfigResult();
            _resultValue.base64Encode = base64Encode;
            _resultValue.boundary = boundary;
            _resultValue.gzip = gzip;
            _resultValue.id = id;
            _resultValue.parts = parts;
            _resultValue.rendered = rendered;
            return _resultValue;
        }
    }
}
