# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

SNAKE_TO_CAMEL_CASE_TABLE = {
    "base64_encode": "base64Encode",
}

CAMEL_TO_SNAKE_CASE_TABLE = {
    "base64Encode": "base64_encode",
}
