// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package cloudinit

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type Config struct {
	pulumi.CustomResourceState

	Base64Encode pulumi.BoolPtrOutput   `pulumi:"base64Encode"`
	Boundary     pulumi.StringPtrOutput `pulumi:"boundary"`
	Gzip         pulumi.BoolPtrOutput   `pulumi:"gzip"`
	Parts        ConfigPartArrayOutput  `pulumi:"parts"`
	// rendered cloudinit configuration
	Rendered pulumi.StringOutput `pulumi:"rendered"`
}

// NewConfig registers a new resource with the given unique name, arguments, and options.
func NewConfig(ctx *pulumi.Context,
	name string, args *ConfigArgs, opts ...pulumi.ResourceOption) (*Config, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Parts == nil {
		return nil, errors.New("invalid value for required argument 'Parts'")
	}
	var resource Config
	err := ctx.RegisterResource("cloudinit:index/config:Config", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetConfig gets an existing Config resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetConfig(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ConfigState, opts ...pulumi.ResourceOption) (*Config, error) {
	var resource Config
	err := ctx.ReadResource("cloudinit:index/config:Config", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Config resources.
type configState struct {
	Base64Encode *bool        `pulumi:"base64Encode"`
	Boundary     *string      `pulumi:"boundary"`
	Gzip         *bool        `pulumi:"gzip"`
	Parts        []ConfigPart `pulumi:"parts"`
	// rendered cloudinit configuration
	Rendered *string `pulumi:"rendered"`
}

type ConfigState struct {
	Base64Encode pulumi.BoolPtrInput
	Boundary     pulumi.StringPtrInput
	Gzip         pulumi.BoolPtrInput
	Parts        ConfigPartArrayInput
	// rendered cloudinit configuration
	Rendered pulumi.StringPtrInput
}

func (ConfigState) ElementType() reflect.Type {
	return reflect.TypeOf((*configState)(nil)).Elem()
}

type configArgs struct {
	Base64Encode *bool        `pulumi:"base64Encode"`
	Boundary     *string      `pulumi:"boundary"`
	Gzip         *bool        `pulumi:"gzip"`
	Parts        []ConfigPart `pulumi:"parts"`
}

// The set of arguments for constructing a Config resource.
type ConfigArgs struct {
	Base64Encode pulumi.BoolPtrInput
	Boundary     pulumi.StringPtrInput
	Gzip         pulumi.BoolPtrInput
	Parts        ConfigPartArrayInput
}

func (ConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*configArgs)(nil)).Elem()
}

type ConfigInput interface {
	pulumi.Input

	ToConfigOutput() ConfigOutput
	ToConfigOutputWithContext(ctx context.Context) ConfigOutput
}

func (*Config) ElementType() reflect.Type {
	return reflect.TypeOf((*Config)(nil))
}

func (i *Config) ToConfigOutput() ConfigOutput {
	return i.ToConfigOutputWithContext(context.Background())
}

func (i *Config) ToConfigOutputWithContext(ctx context.Context) ConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ConfigOutput)
}

type ConfigOutput struct {
	*pulumi.OutputState
}

func (ConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Config)(nil))
}

func (o ConfigOutput) ToConfigOutput() ConfigOutput {
	return o
}

func (o ConfigOutput) ToConfigOutputWithContext(ctx context.Context) ConfigOutput {
	return o
}

func init() {
	pulumi.RegisterOutputType(ConfigOutput{})
}
