// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CloudInit.Outputs
{

    [OutputType]
    public sealed class ConfigPart
    {
        public readonly string Content;
        public readonly string? ContentType;
        public readonly string? Filename;
        public readonly string? MergeType;

        [OutputConstructor]
        private ConfigPart(
            string content,

            string? contentType,

            string? filename,

            string? mergeType)
        {
            Content = content;
            ContentType = contentType;
            Filename = filename;
            MergeType = mergeType;
        }
    }
}
