// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CloudInit.Outputs
{

    [OutputType]
    public sealed class GetConfigPartResult
    {
        /// <summary>
        /// Body content for the part.
        /// </summary>
        public readonly string Content;
        /// <summary>
        /// A MIME-style content type to report in the header for the part. Defaults to `text/plain`
        /// </summary>
        public readonly string ContentType;
        /// <summary>
        /// A filename to report in the header for the part.
        /// </summary>
        public readonly string? Filename;
        /// <summary>
        /// A value for the `X-Merge-Type` header of the part, to control [cloud-init merging behavior](https://cloudinit.readthedocs.io/en/latest/reference/merging.html).
        /// </summary>
        public readonly string? MergeType;

        [OutputConstructor]
        private GetConfigPartResult(
            string content,

            string contentType,

            string? filename,

            string? mergeType)
        {
            Content = content;
            ContentType = contentType;
            Filename = filename;
            MergeType = mergeType;
        }
    }
}
