// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudinit;

import com.pulumi.cloudinit.ConfigArgs;
import com.pulumi.cloudinit.Utilities;
import com.pulumi.cloudinit.inputs.ConfigState;
import com.pulumi.cloudinit.outputs.ConfigPart;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * @deprecated
 * This resource is deprecated.
 * Please use the getConfig data source instead.
 * 
 */
@Deprecated /* This resource is deprecated.
Please use the getConfig data source instead. */
@ResourceType(type="cloudinit:index/config:Config")
public class Config extends com.pulumi.resources.CustomResource {
    @Export(name="base64Encode", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> base64Encode;

    public Output<Optional<Boolean>> base64Encode() {
        return Codegen.optional(this.base64Encode);
    }
    @Export(name="boundary", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> boundary;

    public Output<Optional<String>> boundary() {
        return Codegen.optional(this.boundary);
    }
    @Export(name="gzip", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> gzip;

    public Output<Optional<Boolean>> gzip() {
        return Codegen.optional(this.gzip);
    }
    @Export(name="parts", refs={List.class,ConfigPart.class}, tree="[0,1]")
    private Output<List<ConfigPart>> parts;

    public Output<List<ConfigPart>> parts() {
        return this.parts;
    }
    /**
     * rendered cloudinit configuration
     * 
     */
    @Export(name="rendered", refs={String.class}, tree="[0]")
    private Output<String> rendered;

    /**
     * @return rendered cloudinit configuration
     * 
     */
    public Output<String> rendered() {
        return this.rendered;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Config(String name) {
        this(name, ConfigArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Config(String name, ConfigArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Config(String name, ConfigArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("cloudinit:index/config:Config", name, args == null ? ConfigArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private Config(String name, Output<String> id, @Nullable ConfigState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("cloudinit:index/config:Config", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Config get(String name, Output<String> id, @Nullable ConfigState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Config(name, id, state, options);
    }
}
