// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudinit;

import com.pulumi.cloudinit.inputs.ConfigPartArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ConfigArgs extends com.pulumi.resources.ResourceArgs {

    public static final ConfigArgs Empty = new ConfigArgs();

    @Import(name="base64Encode")
    private @Nullable Output<Boolean> base64Encode;

    public Optional<Output<Boolean>> base64Encode() {
        return Optional.ofNullable(this.base64Encode);
    }

    @Import(name="boundary")
    private @Nullable Output<String> boundary;

    public Optional<Output<String>> boundary() {
        return Optional.ofNullable(this.boundary);
    }

    @Import(name="gzip")
    private @Nullable Output<Boolean> gzip;

    public Optional<Output<Boolean>> gzip() {
        return Optional.ofNullable(this.gzip);
    }

    @Import(name="parts", required=true)
    private Output<List<ConfigPartArgs>> parts;

    public Output<List<ConfigPartArgs>> parts() {
        return this.parts;
    }

    private ConfigArgs() {}

    private ConfigArgs(ConfigArgs $) {
        this.base64Encode = $.base64Encode;
        this.boundary = $.boundary;
        this.gzip = $.gzip;
        this.parts = $.parts;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ConfigArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ConfigArgs $;

        public Builder() {
            $ = new ConfigArgs();
        }

        public Builder(ConfigArgs defaults) {
            $ = new ConfigArgs(Objects.requireNonNull(defaults));
        }

        public Builder base64Encode(@Nullable Output<Boolean> base64Encode) {
            $.base64Encode = base64Encode;
            return this;
        }

        public Builder base64Encode(Boolean base64Encode) {
            return base64Encode(Output.of(base64Encode));
        }

        public Builder boundary(@Nullable Output<String> boundary) {
            $.boundary = boundary;
            return this;
        }

        public Builder boundary(String boundary) {
            return boundary(Output.of(boundary));
        }

        public Builder gzip(@Nullable Output<Boolean> gzip) {
            $.gzip = gzip;
            return this;
        }

        public Builder gzip(Boolean gzip) {
            return gzip(Output.of(gzip));
        }

        public Builder parts(Output<List<ConfigPartArgs>> parts) {
            $.parts = parts;
            return this;
        }

        public Builder parts(List<ConfigPartArgs> parts) {
            return parts(Output.of(parts));
        }

        public Builder parts(ConfigPartArgs... parts) {
            return parts(List.of(parts));
        }

        public ConfigArgs build() {
            if ($.parts == null) {
                throw new MissingRequiredPropertyException("ConfigArgs", "parts");
            }
            return $;
        }
    }

}
