// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

import * as utilities from "../utilities";

export interface ConfigPart {
    /**
     * Body content for the part.
     */
    content: pulumi.Input<string>;
    /**
     * A MIME-style content type to report in the header for the part. Defaults to `text/plain`
     */
    contentType?: pulumi.Input<string | undefined>;
    /**
     * A filename to report in the header for the part.
     */
    filename?: pulumi.Input<string | undefined>;
    /**
     * A value for the `X-Merge-Type` header of the part, to control [cloud-init merging behavior](https://cloudinit.readthedocs.io/en/latest/reference/merging.html).
     */
    mergeType?: pulumi.Input<string | undefined>;
}

export interface GetConfigPart {
    /**
     * Body content for the part.
     */
    content: string;
    /**
     * A MIME-style content type to report in the header for the part. Defaults to `text/plain`
     */
    contentType?: string;
    /**
     * A filename to report in the header for the part.
     */
    filename?: string;
    /**
     * A value for the `X-Merge-Type` header of the part, to control [cloud-init merging behavior](https://cloudinit.readthedocs.io/en/latest/reference/merging.html).
     */
    mergeType?: string;
}
/**
 * getConfigPartProvideDefaults sets the appropriate defaults for GetConfigPart
 */
export function getConfigPartProvideDefaults(val: GetConfigPart): GetConfigPart {
    return {
        ...val,
        contentType: (val.contentType) ?? "text/plain",
    };
}

export interface GetConfigPartArgs {
    /**
     * Body content for the part.
     */
    content: pulumi.Input<string>;
    /**
     * A MIME-style content type to report in the header for the part. Defaults to `text/plain`
     */
    contentType?: pulumi.Input<string | undefined>;
    /**
     * A filename to report in the header for the part.
     */
    filename?: pulumi.Input<string | undefined>;
    /**
     * A value for the `X-Merge-Type` header of the part, to control [cloud-init merging behavior](https://cloudinit.readthedocs.io/en/latest/reference/merging.html).
     */
    mergeType?: pulumi.Input<string | undefined>;
}
/**
 * getConfigPartArgsProvideDefaults sets the appropriate defaults for GetConfigPartArgs
 */
export function getConfigPartArgsProvideDefaults(val: GetConfigPartArgs): GetConfigPartArgs {
    return {
        ...val,
        contentType: (val.contentType) ?? "text/plain",
    };
}
